[build]
  base = "mobile"
  command = "npx expo export --platform web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  DARK_MODE = "class"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
