import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type WhatsAppLeadStatus =
  | 'New'
  | 'Contacted'
  | 'Qualified'
  | 'Converted'
  | 'Closed';

export interface WhatsAppLead {
  id: string;
  // Customer Info
  customerName: string;
  mobile: string;
  whatsappNumber?: string;

  // Product Info
  productCategory: string;
  bankName: string;
  leadSource: 'WhatsApp Share';

  // Requirement Details
  loanAmount?: string;
  propertyType?: string;
  preferredCallbackTime?: string;

  // Location (optional)
  pincode?: string;
  city?: string;

  // Status
  status: WhatsAppLeadStatus;
  assignedTo?: string;
  notes?: string;

  // Timestamps
  timestamp: string;
  createdAt: string;
  updatedAt?: string;
}

interface WhatsAppLeadsStore {
  leads: WhatsAppLead[];

  // Actions
  addLead: (lead: Omit<WhatsAppLead, 'id' | 'leadSource' | 'createdAt' | 'status'>) => WhatsAppLead;
  updateLeadStatus: (leadId: string, status: WhatsAppLeadStatus) => void;
  assignLeadTo: (leadId: string, assignee: string) => void;
  addLeadNote: (leadId: string, note: string) => void;
  getLeadById: (leadId: string) => WhatsAppLead | undefined;
  getLeadsByStatus: (status: WhatsAppLeadStatus) => WhatsAppLead[];
  getLeadsByProduct: (productCategory: string) => WhatsAppLead[];

  // Anti-spam protection
  canCreateLead: (mobile: string, productCategory: string, bankName: string) => boolean;
  getRecentLeads: (mobile: string, productCategory: string, bankName: string) => WhatsAppLead[];

  // Export
  exportLeads: (leads?: WhatsAppLead[]) => string;
}

// Helper function to generate unique ID
const generateLeadId = (): string => {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 9);
  return `WL-${timestamp}-${random}`.toUpperCase();
};

// Helper function to format lead for WhatsApp message
export const formatLeadForWhatsApp = (lead: WhatsAppLead): string => {
  const loanAmountDisplay = lead.loanAmount
    ? lead.loanAmount === 'custom'
      ? 'Custom Amount'
      : LOAN_AMOUNT_LABELS[lead.loanAmount] || lead.loanAmount
    : 'Not provided';

  const propertyTypeDisplay = lead.propertyType
    ? PROPERTY_TYPE_LABELS[lead.propertyType] || lead.propertyType
    : 'Not provided';

  const callbackTimeDisplay = lead.preferredCallbackTime
    ? CALLBACK_TIME_LABELS[lead.preferredCallbackTime] || lead.preferredCallbackTime
    : 'Not provided';

  return `🔔 *New Lead via Paisa Mart (WhatsApp Share)*

📦 *Product:* ${lead.productCategory.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}
🏦 *Bank:* ${lead.bankName}

👤 *Customer:* ${lead.customerName}
📱 *Mobile:* ${lead.mobile}
${lead.whatsappNumber ? `💬 *WhatsApp:* ${lead.whatsappNumber}\n` : ''}
💰 *Loan Amount:* ${loanAmountDisplay}
🏠 *Property Type:* ${propertyTypeDisplay}
📞 *Preferred Callback:* ${callbackTimeDisplay}

🕐 *Time:* ${new Date(lead.timestamp).toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  })}

🆔 *Lead ID:* ${lead.id}
📊 *Status:* ${lead.status}

---
_Generated by Paisa Mart App_`;
};

// Label mappings for display
const LOAN_AMOUNT_LABELS: Record<string, string> = {
  '1000000': '₹10 Lakh',
  '2000000': '₹20 Lakh',
  '3000000': '₹30 Lakh',
  '5000000': '₹50 Lakh',
  '7500000': '₹75 Lakh',
  '10000000': '₹1 Crore',
};

const PROPERTY_TYPE_LABELS: Record<string, string> = {
  'self-occupied': 'Self-occupied',
  'investment': 'Investment',
  'plot-construction': 'Plot+Construction',
};

const CALLBACK_TIME_LABELS: Record<string, string> = {
  'now': 'Now',
  'today-evening': 'Today Evening',
  'tomorrow': 'Tomorrow',
};

export const useWhatsAppLeadsStore = create<WhatsAppLeadsStore>()(
  persist(
    (set, get) => ({
      leads: [],

      addLead: (leadData) => {
        const newLead: WhatsAppLead = {
          ...leadData,
          id: generateLeadId(),
          leadSource: 'WhatsApp Share',
          status: 'New',
          createdAt: new Date().toISOString(),
          timestamp: new Date().toISOString(),
        };

        set((state) => ({
          leads: [newLead, ...state.leads],
        }));

        return newLead;
      },

      updateLeadStatus: (leadId, status) => {
        set((state) => ({
          leads: state.leads.map((lead) =>
            lead.id === leadId
              ? { ...lead, status, updatedAt: new Date().toISOString() }
              : lead
          ),
        }));
      },

      assignLeadTo: (leadId, assignee) => {
        set((state) => ({
          leads: state.leads.map((lead) =>
            lead.id === leadId
              ? { ...lead, assignedTo: assignee, updatedAt: new Date().toISOString() }
              : lead
          ),
        }));
      },

      addLeadNote: (leadId, note) => {
        set((state) => ({
          leads: state.leads.map((lead) =>
            lead.id === leadId
              ? {
                  ...lead,
                  notes: lead.notes ? `${lead.notes}\n\n${note}` : note,
                  updatedAt: new Date().toISOString()
                }
              : lead
          ),
        }));
      },

      getLeadById: (leadId) => {
        return get().leads.find((lead) => lead.id === leadId);
      },

      getLeadsByStatus: (status) => {
        return get().leads.filter((lead) => lead.status === status);
      },

      getLeadsByProduct: (productCategory) => {
        return get().leads.filter((lead) => lead.productCategory === productCategory);
      },

      // Anti-spam protection: Check if user can create a lead
      // Rule: No duplicate leads within 10 minutes for same mobile + product + bank
      canCreateLead: (mobile, productCategory, bankName) => {
        const recentLeads = get().getRecentLeads(mobile, productCategory, bankName);
        return recentLeads.length === 0;
      },

      getRecentLeads: (mobile, productCategory, bankName) => {
        const tenMinutesAgo = Date.now() - 10 * 60 * 1000;

        return get().leads.filter((lead) => {
          const leadTime = new Date(lead.timestamp).getTime();
          return (
            lead.mobile === mobile &&
            lead.productCategory === productCategory &&
            lead.bankName === bankName &&
            leadTime > tenMinutesAgo
          );
        });
      },

      exportLeads: (leadsToExport) => {
        const leads = leadsToExport || get().leads;

        // Create CSV format
        const headers = [
          'Lead ID',
          'Customer Name',
          'Mobile',
          'WhatsApp Number',
          'Product Category',
          'Bank Name',
          'Loan Amount',
          'Property Type',
          'Preferred Callback',
          'Status',
          'Assigned To',
          'Notes',
          'Created At',
        ];

        const rows = leads.map((lead) => [
          lead.id,
          lead.customerName,
          lead.mobile,
          lead.whatsappNumber || '',
          lead.productCategory,
          lead.bankName,
          lead.loanAmount || '',
          lead.propertyType || '',
          lead.preferredCallbackTime || '',
          lead.status,
          lead.assignedTo || '',
          lead.notes || '',
          lead.createdAt,
        ]);

        const csvContent = [
          headers.join(','),
          ...rows.map((row) =>
            row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(',')
          ),
        ].join('\n');

        return csvContent;
      },
    }),
    {
      name: 'whatsapp-leads-storage',
      storage: createJSONStorage(() => AsyncStorage),
    }
  )
);

// Helper function to check if product category supports lead capture
export const shouldCaptureLeadForCategory = (category: string): boolean => {
  const supportedCategories = [
    'home-loans',
    'personal-loans',
    'vehicle-loans',
    'business-loans',
    'life-insurance',
    'health-insurance',
    'motor-insurance',
    'gold-loans',
  ];

  return supportedCategories.includes(category);
};
